version: '3'
services:
  meu_mysql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysql_NET6_container
    hostname: mysql_NET6_service
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=banco-NET6
      - MYSQL_USER=NET6
      - MYSQL_PASSWORD=NET6
